ARG BASE_IMG=quay.io/redhat-github-actions/runner:latest
FROM $BASE_IMG AS imagescan-runner

# relies on ROX_ENDPOINT, ROX_API_TOKEN env vars
# will keep this in an external secret

ENV ROX_ENDPOINT, ROX_API_TOKEN, ROX_AUTH_MACHINE_TO_MACHINE, ROX_CENTRAL_ADDRESS

USER root

RUN  arch="$(uname -m | sed "s/x86_64//")"; arch="${arch:+-$arch}"; curl -f -o roxctl "https://mirror.openshift.com/pub/rhacs/assets/4.3.5/bin/Linux/roxctl${arch}" && \
     chmod +x roxctl && \
     cp -f ./roxctl /usr/local/bin/ && \
     dnf install -y jq

USER $UID

COPY ./generate_uuid.py .

RUN roxctl version && \
    jq --version
